# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HinderApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for HinderApp
  pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
  pod 'YogaKit', '~> 1.6'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'AWSS3'
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'
  pod 'Koloda', '~> 4.3.1'
end
